### ISSUE TITLE
Make sidebar collapsible

### ISSUE THREAD

**Issue by eriknystrom** [csc423-teamproject/break-the-internet#8]
Sidebar is nice but needs to support small screens. 

Make the sidebar collapsible and automatically detect between mobile/desktop user agents.

**Comment by jvanhouter** [comment]
Halfway there - collapse works, need to update button icon to reflect the sidebar functionality.

**Comment by jvanhouter** [comment]
Really late to update this, but sidebar updated - opens with hamburger, closes with close link. Tooltips would be nice, but I can't get them to appear in the correct place consistently.
Sidebar works now, suggest closing.

**Comment by jvanhouter** [comment]
What a difference half an hour makes... tooltips added, closing issue.
