### ISSUE TITLE
Make minimial icon for Nanno's Logo

### ISSUE THREAD

**Issue by eriknystrom** [csc423-teamproject/break-the-internet#9]
Make a smaller logo for Nanno's

200x200?

**Comment by MattHumphries** [comment]
![200x200logo](https://user-images.githubusercontent.com/39308716/48230778-24570c80-e37a-11e8-88c0-f625b2021868.jpg)

**Comment by eriknystrom** [comment]
@jvanhouter New filleted logo looks good. Should we increase the radius or is it sufficient?

**Comment by jvanhouter** [comment]
Fillets do need to be smaller - also, convert to PNG in order to scale if need be.

**Comment by jvanhouter** [comment]
Updated with new Sidenav work - closing.
